### PR TITLE
switched from 0.2.0 to 0.4.0 for coxeter.

### PR DESCRIPTION
**Pull request by Tobias-Dwyer**
Apologies, messed up on the branch name, otherwise I changed a single number for the coxeter version and it looks like in glotzer-lab.jinja you automatically pull dependencies on github(could be wrong about that).

### CODE REVIEW

**Comment by joaander** [comment]
Can you make a new branch off of master and cherry pick this commit onto it?
```
git switch master
git swtich -c coxeter_update
git cherry-pick db80845
```
Make a PR for that branch. I'll merge master up into the v3-beta branch so it also has the new version of coxeter.

The builds check dependencies, but don't automatically install them. Does coxeter use pytest and install its test suite? It would be great to run those tests in `test_template.jinja`. If coxeter installs its tests, this is just:
```
RUN python3 -m pytest coxeter
```

**Comment by Tobias-Dwyer** [comment]
Okay did the cherry picking. Just wondering how to run the coxeter tests. I think coxeter does install its tests. How do I use the test template to run those? (little confused sorry)

**Comment by vyasr** [comment]
@joaander by install tests, do you mean that the tests are part of the MANIFEST and are copied into site-packages by the installation process?

**Comment by joaander** [comment]
> @joaander by install tests, do you mean that the tests are part of the MANIFEST and are copied into site-packages by the installation process? If so, the answer is no; tests must be run out of the repository.

Yes, that's what I was asking. You can use a longer RUN command than my example to check out the source again and run the tests out of source using the installed build. Note that right now `glotzerlab-software` currently only ensures that the packages import. I think it would be good to run the unit tests for all our packages, and we might as well start with coxeter.

**Comment by vyasr** [comment]
@Tobias-Dwyer is it clear what Josh is suggesting? Basically you need to add lines that are basically what you would do on your own machine: check out coxeter, `cd` into it, and run pytest. The main difference is that since it's inside a Docker container script you need to add the `RUN` command to the beginning of the line.

**Comment by Tobias-Dwyer** [comment]
It's partially clear but I still don't understand the syntax totally, will try what josh posted in slack and try to understand the syntax more.

**Comment by joaander** [comment]
Replaced with #15

**Pull request closed without merging**
